name: UHCRunManager
version: 1.0
author: Canjas
main: Canjas.UHCRunManager
api-version: 1.16
commands:
  runstart:
    description: launch uchrun
    permission: samuel.use
  runstop:
    description: stop uchrun
    permission: samuel.use
load: STARTUP